[package]
name = "elfbin"
version = "0.1.0"
edition = "2018"

[dependencies]
binbin = "0.2.0"
structopt = "0.3.14"

[dev-dependencies]
elf = "0.0.10"

[lib]
path = "src/lib.rs"

[[bin]]
name = "elfbin"
path = "src/bin/main.rs"
